### ISSUE TITLE
HPKE support

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#12]
I'm going to borrow code from ppm-prototype to get HPKE message exchange working.

- [x] Construct HPKE sender and receiver in memory and transmit a message in a unit test (#14)
- [x] Put together an aggregator binary that exposes an `hpke-config` endpoint compliant with the PPM spec (#15)
- [x] Once we have figured out configuration (#20), provide HPKE configurations and the address/port to listen on to `aggregator` instead of hard-coding them. (#37)

**Comment by tgeoghegan** [comment]
After some discussion in #37, we've agreed to provide HPKE private keys in the database, encrypted under a key that we will provide to running containers. This intersects with the question of whether the same HPKE config should be used for all tasks (my 2c: no), which means we need to address ppm-specification/#146.

- [ ] hash out https://github.com/abetterinternet/ppm-specification/issues/146
- [ ] Wire up secret encryption key in k8s secrets and use it to obtain HPKE private keys from database

**Comment by tgeoghegan** [comment]
I don't think there's anything outstanding to do here.
