### ISSUE TITLE
Implement `draft-ietf-ppm-dap-07`

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#1669]
[DAP-05](https://datatracker.ietf.org/doc/draft-ietf-ppm-dap/05/) is out and Janus should implement it. We need:

- [x] update to new libprio-rs that does VDAF-06 (#1673)
- [x] update to new libprio-rs that does VDAF-07 (https://github.com/divviup/libprio-rs/issues/701; #1811)
- [x] ping pong topology https://github.com/divviup/janus/pull/1811
- [x] deal with error type changes https://github.com/divviup/janus/pull/1853
- [x] verify that we use appropriate media types when serving HPKE configs, aggregate share requests
- [x] HPKE domain separation strings
- [x] update versions table in README.md (https://github.com/divviup/janus/pull/1676)
- [x] Branch for DAP-04 (https://github.com/divviup/janus/pull/1676)
- [x] Daphne is skipping ahead to draft-ietf-dap-09 <s>re-enable Daphne test once they have a DAP-06 implementation</s>
- [x] re-enable divviup-ts tests once it has a DAP-07 implementation (https://github.com/divviup/janus/pull/2388)
- [x] re-enable Prio3Histogram in-cluster test once divviup-api can deal with DAP-05 (https://github.com/divviup/divviup-api/issues/410, #1743)

[Draft diff](https://author-tools.ietf.org/iddiff?url1=draft-ietf-ppm-dap-04&url2=draft-ietf-ppm-dap-06&difftype=--html)

**Comment by tgeoghegan** [comment]
[DAP-06](https://datatracker.ietf.org/doc/draft-ietf-ppm-dap/06/) is out with a more clear and implementable ping-pong spec, so we'll jump ahead to implementing that.

**Comment by tgeoghegan** [comment]
The wrong commit got tagged as DAP-06, leaving it with the wrong HPKE domain separation strings and an outdated reference to DAF. So we published `draft-ietf-ppm-dap-07` which fixes those issues, and that's what we're going to implement in Janus.
