### ISSUE TITLE
Implement `draft-ietf-ppm-dap-09`

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#2389]
Janus should implement the latest draft of the standard.

- [x] update to a new libprio-rs that does VDAF-08 (#2477)
- [x] HPKE domain separation strings (#2479)
- [x] [Section 4.1.2](https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap-09#section-4.1.2-3): "The Leader MUST select a batch that has not yet been associated with a collection job." (#2391)
- [x] [Section 4.1.2](https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap-09#section-4.1.2-4): `max_batch_size` is now optional in fixed size tasks (#2551)
- [x] [Section 4.5.2.2](https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap-09#section-4.5.2.2-20): "If for whatever reason the Leader must abandon the aggregation job, it SHOULD send an HTTP DELETE request to the aggregation job URI so that the Helper knows it can clean up its state." (#2530, https://github.com/divviup/public-docs/pull/49)
- [x] [Section 4.6.1](https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap-09#section-4.6.1-16): Ensure we comply with the new MUST: "If the Leader has a pending aggregation job that overlaps with the batch and aggregation parameter for the collection job, the Leader MUST first complete the aggregation job before proceeding and requesting an aggregate share from the Helper. This avoids a race condition between aggregation and collection jobs that can yield trivial batch mismatch errors." (Already satisfied by Janus; [see comment below](https://github.com/divviup/janus/issues/2389#issuecomment-1900915729)
- [x] update versions table in README.md (#2468)
- [x] Branch for DAP-07 ([`release/0.6`](https://github.com/divviup/janus/tree/release/0.6))
- [x] update divviup-ts integration tests once that component supports -09
- [x] update Daphne integration tests once it supports -09
- [x] Implement [`draft-wang-ppm-dap-taskprov-06`](https://datatracker.ietf.org/doc/draft-wang-ppm-dap-taskprov/06/) (#2598)
- [x] ~Sync up with changes to [`draft-dcook-ppm-dap-interop-test-design`](https://github.com/divergentdave/draft-dcook-ppm-dap-interop-test-design/issues/43)~ No such changes should be needed

[Diff between DAP-07 and -09](https://author-tools.ietf.org/iddiff?url1=draft-ietf-ppm-dap-07&url2=draft-ietf-ppm-dap-09&difftype=--html)

**Comment by cjpatton** [comment]
Daphne *should* support 09 already, but integration tests probably need to change in the wake of some major service changes done by @mendess. Let's sync up in the new year.

**Comment by divergentdave** [comment]
We should fix #2466 together with draft-09 implementation.

**Comment by branlwyd** [comment]
We need to include the change that fixed-size current-batch requests can return each batch at most once, implemented in https://github.com/divviup/janus/pull/2391.

**Comment by tgeoghegan** [comment]
Through source inspection, I've satisfied myself that Janus already complies with the new requirement in [Section 4.6.1](https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap-09#section-4.6.1-16): the collection job driver will not step a collection job unless it is in the `COLLECTABLE` state, and that only happens in `AggregationJobWriter::write` if all the pertinent batches are themselves in the `CLOSED` state, meaning no further reports may be aggregated into them, which is equivalent to the aggregation jobs being complete.

**Comment by tgeoghegan** [comment]
We've long since shipped our DAP-09 implementation.
