### ISSUE TITLE
Add tests (and fix related bugs) for idempotence of resource creation

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/janus#998]
Review of #936 uncovered some subtleties about error handling when trying to mutate resources with PUT requests ([comment thread](https://github.com/divviup/janus/pull/936#discussion_r1099171509)). We need to add tests that show we handle various scenarios as expected:

- [x] add test proving that PUT report is idempotent (#1013)
- [x] add test proving that mutating a report with PUT fails with expected error (#1013)
- [x] add test proving that PUT collection job is idempotent (#1036)
- [x] add test proving that mutating a collection job with PUT fails with expected error (#1036)
- [x] add test proving that PUT aggregation job is idempotent (#1033)
- [x] add test proving that mutating an aggregation job with PUT fails with expected error (#1033)
- [x] add test proving that POST aggregation share is idempotent ([see note below](https://github.com/divviup/janus/issues/998#issuecomment-1440659531))

...and of course to fix whatever bugs are uncovered by the new tests.

**Comment by divergentdave** [comment]
We should be sure to test that collection job PUT is idempotent for `current_batch` queries in particular, per https://github.com/divviup/janus/pull/936/files#r1100491397.

**Comment by tgeoghegan** [comment]
It turns out that we already have a test showing that POST to aggregate shares is idempotent. [This portion of `aggregator::tests::aggregate_share_request`](https://github.com/divviup/janus/blob/368ceb85e4b3df68511f436ef98e3b49dd0ff171/aggregator/src/aggregator.rs#L9332) sends valid aggregate share requests multiple times and verifies that the requests succeed each time.

**Comment by tgeoghegan** [comment]
I think we have all the tests we need in place now, so I'm closing this.
